version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: tp-foyer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfoyer
    ports:
      - "3306:3306"
    networks:
      - tp-network

  tpfoyer:
    image: tp-foyer-app:1.0
    container_name: tp-foyer-container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tpfoyer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
    networks:
      - tp-network

networks:
  tp-network:
    driver: bridge
